# Generated by Django 5.2.3 on 2025-06-21 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео')),
                ('audio_kg', models.FileField(upload_to='manuals/', verbose_name='Аудио (Кыргызский)')),
                ('audio_uz', models.FileField(upload_to='manuals/', verbose_name='Аудио (Узбекский)')),
                ('audio_ru', models.FileField(upload_to='manuals/', verbose_name='Аудио (Русский)')),
            ],
            options={
                'verbose_name': 'Справочник учителя',
                'verbose_name_plural': 'Справочники учителей',
            },
        ),
    ]
