# Generated by Django 5.2.3 on 2025-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('ADMIN', 'Администратор')], max_length=10, verbose_name='Роль'),
        ),
    ]
