# Generated by Django 5.2.3 on 2025-06-21 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
                ('total_questions', models.IntegerField(verbose_name='Количество вопросов')),
                ('total_points', models.IntegerField(verbose_name='Общее количество баллов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_microphone_required', models.BooleanField(default=False, verbose_name='Требуется микрофон')),
                ('timer', models.IntegerField(verbose_name='Время на экзамен (мин)')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('TP', 'Текстовое поле'), ('FT', 'Фотография'), ('IO', 'Интерактивный ответ')], max_length=20, verbose_name='Тип вопроса')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок вопроса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение (опционально)')),
                ('score', models.IntegerField(verbose_name='Баллы за вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
