# Generated by Django 5.2.3 on 2025-06-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
