# Generated by Django 5.2.3 on 2025-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='Изображение ответа'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа'),
        ),
    ]
