# Generated by Django 5.2.3 on 2025-06-21 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название потока')),
                ('stream_link', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Ссылка на поток (UUID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.CreateModel(
            name='StreamStudentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='Имя студента')),
                ('student_surname', models.CharField(max_length=255, verbose_name='Фамилия студента')),
                ('total_score', models.IntegerField(verbose_name='Общее количество баллов')),
                ('total_time', models.IntegerField(verbose_name='Время прохождения (мин)')),
                ('passed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('is_cheated', models.BooleanField(default=False, verbose_name='Нарушил правила (списывание)')),
            ],
            options={
                'verbose_name': 'Результат студента',
                'verbose_name_plural': 'Результаты студентов',
            },
        ),
    ]
