# Generated by Django 5.2.3 on 2025-06-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamstudentresult',
            name='is_cheated',
        ),
    ]
