# Generated by Django 5.2.3 on 2025-06-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_remove_streamstudentresult_is_cheated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamstudentresult',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='streamstudentresult',
            name='student_surname',
        ),
        migrations.AddField(
            model_name='streamstudentresult',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='ФИО студента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamstudentresult',
            name='is_cheated',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нарушение (если было)'),
        ),
    ]
